# Generated by Django 4.1.5 on 2023-02-07 20:52

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_old_price_currency_product_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='NGN', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=19),
        ),
    ]
